#ifndef PLATFORMER_ENGINE_CLIENTNETWORKMANAGER_HPP
#define PLATFORMER_ENGINE_CLIENTNETWORKMANAGER_HPP
namespace platformer_engine {
    class ClientNetworkManager{

    };
}
#endif //PLATFORMER_ENGINE_CLIENTNETWORKMANAGER_HPP
