#ifndef PLATFORMER_ENGINE_PROTOCOLDEFINITIONS_HPP
#define PLATFORMER_ENGINE_PROTOCOLDEFINITIONS_HPP

constexpr int NET_PROTOCOL_VERSION_MAJOR = 0;
constexpr int NET_PROTOCOL_VERSION_MINOR = 5;
constexpr int NET_REQUEST_CONNECT = 10;
constexpr int NET_REQUEST_LEAVE_SERVER = 11;
constexpr int NET_REQUEST_PING = 12;
constexpr int NET_KICK_CLIENT = 13;
constexpr int NET_CREATE_GAMEOBJECT = 14;
constexpr int NET_DESTROY_GAMEOBJECT = 15;
constexpr int NET_UPDATE_GAMEOBJECT_TRANSFORM = 16;

#endif //PLATFORMER_ENGINE_PROTOCOLDEFINITIONS_HPP
