name: 'C++ Clang Tidy Linter'

on: pull_request

jobs:
  cpp-linter:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x64-linux
    steps:
      - uses: actions/checkout@v3
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - name: 'Install CMake'
        uses: lukka/get-cmake@latest

      - name: 'Setup vcpkg'
        uses: lukka/run-vcpkg@v10
        with:
          appendedCacheKey: -${{ matrix.triplet }}

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ninja-multi-vcpkg
          buildPreset: ninja-multi-vcpkg
          testPreset: ninja-multi-vcpkg

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :warning: **cpp-linter** found some issues. Please check the linter and fix the warnings :)