#Clone MarioGame repo, update platformer engine submodule, create branch, push changes and open pull request to main
# Path: .github/workflows/update-game-modules.yml

name: 'Update game modules'

on:
  # push:
  #   branches:
  #     - master
  pull_request:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      #checkout repo MarioGame

      - name: 'Create new branch'
        uses: GuillaumeFalourd/create-other-repo-branch-action@v1.4
        with:
          repository_owner: SPC-H-Avans
          repository_name: MarioGame
          new_branch_name: 'update-platformer-engine-${{ github.run_number }}'
          access_token: ${{ secrets.PAT}}

      - name: 'Checkout MarioGame'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: SPC-H-Avans/MarioGame
          ref: 'update-platformer-engine-${{ github.run_number }}'
          submodules: recursive

      #update platformer engine submodule
      - name: 'Update platformer engine submodule'
        run: |
          cd MarioGame
          git submodule update --remote --merge

      # create new branch with github action script

      #push changes
      - name: 'Upload changes to repo'
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-directory: 'MarioGame'
          user-email: '41898282+github-actions[bot]@users.noreply.github.com'
          user-name: 'github-actions[bot]'
          target-branch: 'update-platformer-engine-${{ github.run_number }}'
          destination-github-username: SPC-H-Avans
          destination-repository-name: MarioGame
        
