name: "Build and run tests with memory check"

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  RUN_MEMORY_CHECK: true
jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: valgrind-os
            triplet: x64-linux

    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      XDG_RUNTIME_DIR: "/tmp/swaywm"

    steps:
      - name: 'Install SDL2 dev'
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: 'Install CMake'
        uses: lukka/get-cmake@latest

      - name: 'Setup vcpkg'
        uses: lukka/run-vcpkg@v10

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ninja-multi-vcpkg
          buildPreset: ninja-multi-valgrind

      - name: 'Install Valgrind'
        if: ${{ env.RUN_MEMORY_CHECK == 'true' }}
        run: |
          sudo apt install valgrind -y
          echo "Valgrind installed"

      #      - name: 'Run executable'
      #        run: |
      #          ./builds/ninja-multi-vcpkg/Release/platformer-engine-exec

      - name: Run Tests with Valgrind
        run: |
          valgrind --leak-check=full --xml=yes --xml-file=unit_tests_valgrind.xml ./builds/ninja-multi-vcpkg/Debug/platformer-engine-exec --main-stacksize=1000000000

      - name: Valgrind Memory check
        if: ${{ env.RUN_MEMORY_CHECK == 'true' }}
        run: |
          echo "Checking Valgrind xml ..."
            sudo chmod +x check-memory.sh
            ./check-memory.sh