name: "Build and run tests with memory check"

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  RUN_MEMORY_CHECK: true
jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: valgrind-os
            triplet: x64-linux

    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      XDG_RUNTIME_DIR: "/tmp/swaywm"

    steps:
      - name: 'Install SDL2 dev'
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: 'Install CMake'
        uses: lukka/get-cmake@latest

      - name: 'Setup vcpkg'
        uses: lukka/run-vcpkg@v10

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ninja-multi-vcpkg
          buildPreset: ninja-multi-valgrind

      - name: 'Run doctor memory'
        run: |
          drmemory -- ./builds/ninja-multi-vcpkg/Debug/platformer-engine-exec